application: hydro-test
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/public/images/favicon.ico
  upload: static/public/images/favicon.ico
  
- url: /s
  static_dir: static/public

- url: /.*
  script: example.application
  secure: always

libraries:
- name: jinja2
  version: latest